# Generated by Django 5.1.6 on 2025-09-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookTrak', '0002_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='times_issued',
            field=models.IntegerField(default=0),
        ),
    ]
