# Generated by Django 5.1.6 on 2025-09-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookTrak', '0003_book_times_issued'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='saved_books',
            field=models.JSONField(default=list),
        ),
    ]
