# Generated by Django 5.1.6 on 2025-09-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookTrak', '0004_userprofile_saved_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cart_items',
            field=models.JSONField(default=list),
        ),
    ]
